name: classtab_catalog
description: A Flutter application for cataloging and viewing classical guitar tablatures from classtab.org

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # HTTP requests
  http: ^1.1.0
  dio: ^5.3.2
  
  # HTML parsing
  html: ^0.15.4
  
  # Local storage
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # File handling
  archive: ^4.0.7
  path: ^1.8.3
  
  # MIDI playback
  flutter_midi_command: ^0.5.3
  
  # State management
  provider: ^6.1.1
  
  # Search functionality
  flutter_typeahead: ^5.2.0
  
  # Loading indicators
  flutter_spinkit: ^5.2.0
  
  # URL launcher
  url_launcher: ^6.2.1
  
  # YouTube player
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/sounds/
  
  # fonts:
  #   - family: RobotoMono
  #     fonts:
  #       - asset: fonts/RobotoMono-Regular.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #         weight: 700