name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        platform: [android, web]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (for Android)
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        if: matrix.platform == 'android'
        run: |
          if [ -n "$ANDROID_HOME" ] || [ -n "$ANDROID_SDK_ROOT" ]; then
            echo "Setting up Gradle properties for CI..."
            echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8" >> android/gradle.properties
            echo "org.gradle.parallel=false" >> android/gradle.properties
            echo "org.gradle.daemon=false" >> android/gradle.properties
            flutter build apk --debug
          else
            echo "Android SDK not found, skipping Android build"
            echo "This is expected in environments without Android SDK"
            exit 0
          fi

      - name: Build Web
        if: matrix.platform == 'web'
        run: flutter build web --debug